services:
  django:
    container_name: django_server
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000 --cert-file testmastersite.crt --key-file testmastersite.key"
    volumes:
      - .:/usr/src/app/my-website
    ports:
      - "8000:8000"
    restart: unless-stopped