# Generated by Django 4.2.17 on 2024-12-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('date_added', models.DateField(verbose_name='date published')),
                ('recipe_desc', models.CharField(max_length=400)),
                ('amt_served', models.IntegerField(default=1)),
                ('recipe_img', models.ImageField(default=None, upload_to='recipe_images', verbose_name='recipe image')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=1)),
                ('measurement', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.recipe')),
            ],
        ),
    ]
