# Generated by Django 4.2.17 on 2024-12-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0004_recipestep_recipe_alter_ingredient_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('breakfast', 'Breakfast'), ('dessert', 'Dessert'), ('large_group', 'Large Groups/Parties'), ('dinner', 'Dinner')], default=None, max_length=20, verbose_name='recipe type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('pint', 'Pint(s)'), ('tbsp', 'Tablespoon(s)'), ('g', 'Gram(s)'), ('cup', 'Cup(s)'), ('floz', 'Fluid Ounce(s)'), ('mL', 'Milliliter(s)'), ('tsp', 'Teaspoon(s)'), ('gallon', 'Gallon(s)'), ('quart', 'Quart(s)'), ('lbs', 'Pound(s)')], max_length=200, verbose_name='measurement'),
        ),
    ]
